
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hp
 */
public class enrollment extends javax.swing.JFrame {

    /**
     * Creates new form enrollment
     */
    public enrollment() {
        initComponents();
        showdetailsen();
        dynamicpanel1.setVisible(true);
        insert.setVisible(false);
        update.setVisible(false);
        delete.setVisible(false);
        view.setVisible(false);
    }
    
    public ArrayList<uenroll>enList(){
        ArrayList<uenroll>enList=new ArrayList<>();
         try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connect=DriverManager.getConnection("jdbc:mysql://localhost:3306/login?zeroDateTimeBehavior=convertToNull","root","");
            String query="select * from enrollment";
            Statement st=connect.createStatement();
            ResultSet rst=st.executeQuery(query);
            uenroll enro;
            while(rst.next()){
                enro=new uenroll(rst.getString("IndexNo"), rst.getString("Faculty"), rst.getString("Course"), rst.getString("Semister"), rst.getString("E_mail"), rst.getString("Fee"), rst.getString("Credits"), rst.getString("ChoiceSubject1"), rst.getString("ChoiceSubject2"), rst.getString("CompulsarySubject"));
                enList.add(enro);           
            }
         
         } 
         catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
         }
         return enList;
    }
    public void showdetailsen(){
        ArrayList<uenroll>list=enList();
        DefaultTableModel table=(DefaultTableModel)etable.getModel();
        Object[] row=new Object[10];
        for(int k=0;k<list.size();k++){
            row[0]=list.get(k).getIndexNo();
            row[1]=list.get(k).getFaculty();
            row[2]=list.get(k).getCourse();
            row[3]=list.get(k).getSemister();
            row[4]=list.get(k).getE_mail();
            row[5]=list.get(k).getFee();
            row[6]=list.get(k).getCredits();
            row[7]=list.get(k).getChoiceSubject1();
            row[8]=list.get(k).getChoiceSubject2();
            row[9]=list.get(k).getCompulsarySubject();
            table.addRow(row);
            
        }
    }
   
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dynamicpanel1 = new javax.swing.JPanel();
        view = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        etable = new javax.swing.JTable();
        insert = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        enfaculty = new javax.swing.JComboBox<>();
        encourse = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ensemi = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        enfee = new javax.swing.JTextField();
        enindex = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        encredits = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        enmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        entable = new javax.swing.JTable();
        jSeparator8 = new javax.swing.JSeparator();
        enchoice1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        enchoice2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        encom1 = new javax.swing.JTextField();
        update = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        euindex = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        eufee = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        eufac = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        eucourse = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        eusemi = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        eucredits = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        eucom = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        eucho1 = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        eucho2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        eumail = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator15 = new javax.swing.JSeparator();
        eusearch = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        delete = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        edel = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dynamicpanel1.setBackground(new java.awt.Color(51, 51, 51));
        dynamicpanel1.setPreferredSize(new java.awt.Dimension(922, 450));

        etable.setBackground(new java.awt.Color(51, 51, 51));
        etable.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        etable.setForeground(new java.awt.Color(255, 255, 255));
        etable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Index No", "Faculty", "Course", "Semister", "Compulsory Subjects ", "Choice Subjects", "Fee", "Credits"
            }
        ));
        jScrollPane9.setViewportView(etable);

        javax.swing.GroupLayout viewLayout = new javax.swing.GroupLayout(view);
        view.setLayout(viewLayout);
        viewLayout.setHorizontalGroup(
            viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE)
        );
        viewLayout.setVerticalGroup(
            viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        insert.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Index No  :");

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Faculty  :");

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Course  :");

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fee    :");

        enfaculty.setBackground(new java.awt.Color(51, 51, 51));
        enfaculty.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        enfaculty.setForeground(new java.awt.Color(255, 255, 255));
        enfaculty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "School of Engineering", "School of Computing", "School of Business", " ", " " }));

        encourse.setBackground(new java.awt.Color(51, 51, 51));
        encourse.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        encourse.setForeground(new java.awt.Color(255, 255, 255));
        encourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Civil Engineering", "Electrical Engineering", "Computer Science", "Business Management" }));
        encourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encourseActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(51, 51, 51));
        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Credits  :");

        jLabel8.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Semister  :");

        ensemi.setBackground(new java.awt.Color(51, 51, 51));
        ensemi.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        ensemi.setForeground(new java.awt.Color(255, 255, 255));
        ensemi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semister 1", "Semister 2", "Semister 3", "Semister 4", "Semister 5", "Semister 6", "Semister 7", "Semister 8" }));

        enfee.setBackground(new java.awt.Color(51, 51, 51));
        enfee.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        enfee.setForeground(new java.awt.Color(255, 255, 255));
        enfee.setBorder(null);

        enindex.setBackground(new java.awt.Color(51, 51, 51));
        enindex.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        enindex.setForeground(new java.awt.Color(255, 255, 255));
        enindex.setBorder(null);

        encredits.setBackground(new java.awt.Color(51, 51, 51));
        encredits.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        encredits.setForeground(new java.awt.Color(255, 255, 255));
        encredits.setBorder(null);

        jButton6.setBackground(new java.awt.Color(51, 51, 51));
        jButton6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("SAVE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(51, 51, 51));
        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("E-mail  :");

        enmail.setBackground(new java.awt.Color(51, 51, 51));
        enmail.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        enmail.setForeground(new java.awt.Color(255, 255, 255));
        enmail.setBorder(null);
        enmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enmailActionPerformed(evt);
            }
        });

        entable.setBackground(new java.awt.Color(51, 51, 51));
        entable.setFont(new java.awt.Font("Comic Sans MS", 0, 9)); // NOI18N
        entable.setForeground(new java.awt.Color(255, 255, 255));
        entable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Mathematics", "EE101", "8", "3000"},
                {"Alternative current theory", "EE202", "8", "3000"},
                {"Basic theory", "EE103", "3", "2500"},
                {"Electric theory", "EE104", "4", "2800"},
                {"Alternative theory2", "EE201", "4", "2800"},
                {"electronic circuits", "EE203", "3", "2500"},
                {"Mathematics2", "EE301", "8", "3500"},
                {"Mathematics3", "EE401", "8", "3500"},
                {"Transformers theory", "EE302", "4", "3000"},
                {"Basic theory2", "EE303", "3", "2800"},
                {"Power system", "EE402", "4", "3000"},
                {"Power system2", "EE403", "3", "2800"},
                {"Electric theory2", "EE501", "8", "3500"},
                {"Electronic theory2", "EE502", "4", "3200"},
                {"Transformer current2", "EE503", "3", "3000"},
                {"Aletrnative theory4", "EE601", "8", "3600"},
                {"Electronics", "EE602", "4", "3000"},
                {"Electrical theory4", "EE603", "3", "2800"},
                {"Mathematics4(4th yr)", "EE701", "8", "4000"},
                {"Basic theory3(4th yr)", "EE702", "8", "4000"},
                {"Electronic theory3(4th yr)", "EE801", "8", "4000"},
                {"Mathematics5(4th yr)", "EE802", "8", "4000"},
                {"ComputerSystem", "CS101", "4", "2800"},
                {"Mathematics", "CS102", "3", "2800"},
                {"Programming", "CS103", "8", "3000"},
                {"DSA", "CS201", "8", "4000"},
                {"Mathematical methods", "CS202", "4", "3800"},
                {"FCS", "CS203", "3", "3500"},
                {"DSA2", "CS301", "8", "4000"},
                {"FCS2", "CS302", "3", "3000"},
                {"Mathematics2", "CS303", "4", "3500"},
                {"Computersystem2", "CS401", "8", "4000"},
                {"Programming2", "CS402", "4", "3500"},
                {"programming concepts", "CS403", "3", "3000"},
                {"mathematics4", "CS502", "4", "3500"},
                {"DSA3", "CS501", "8", "4000"},
                {"Programming4", "CS503", "3", "3000"},
                {"Mathematics 5", "CS601", "8", "4000"},
                {"FCS3", "CS602", "4", "3500"},
                {"DSA4", "CS603", "3", "3000"},
                {"automata theory", "CS701", "8", "4000"},
                {"Programming concepts2", "CS702", "8", "4000"},
                {"Mathematics6", "CS703", "8", "4000"},
                {"Mathematics7", "CS801", "8", "4000"},
                {"Programming6", "CS802", "8", "4000"},
                {null, "CS803", "8", "4000"},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Subject Name", "SubjectCode", "Credits", "Fee"
            }
        ));
        jScrollPane1.setViewportView(entable);

        enchoice1.setBackground(new java.awt.Color(51, 51, 51));
        enchoice1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        enchoice1.setForeground(new java.awt.Color(255, 255, 255));
        enchoice1.setBorder(null);

        jLabel18.setBackground(new java.awt.Color(51, 51, 51));
        jLabel18.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Choice Sub Code 1  :");

        jLabel19.setBackground(new java.awt.Color(51, 51, 51));
        jLabel19.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Choice Sub Code 2 :");

        enchoice2.setBackground(new java.awt.Color(51, 51, 51));
        enchoice2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        enchoice2.setForeground(new java.awt.Color(255, 255, 255));
        enchoice2.setBorder(null);

        jLabel20.setBackground(new java.awt.Color(51, 51, 51));
        jLabel20.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Compul sub Code 1:");

        encom1.setBackground(new java.awt.Color(51, 51, 51));
        encom1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        encom1.setForeground(new java.awt.Color(255, 255, 255));
        encom1.setBorder(null);

        javax.swing.GroupLayout insertLayout = new javax.swing.GroupLayout(insert);
        insert.setLayout(insertLayout);
        insertLayout.setHorizontalGroup(
            insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel17)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(40, 40, 40)
                .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, insertLayout.createSequentialGroup()
                        .addComponent(encredits, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6)
                        .addGap(199, 199, 199))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, insertLayout.createSequentialGroup()
                        .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ensemi, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(encourse, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator7)
                                .addComponent(enmail, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                            .addComponent(enfaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enindex, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enfee, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, insertLayout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(enchoice1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(insertLayout.createSequentialGroup()
                                .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20))
                                .addGap(18, 18, 18)
                                .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator10)
                                    .addComponent(jSeparator9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(enchoice2)
                                    .addComponent(encom1))))
                        .addContainerGap(138, Short.MAX_VALUE))))
        );
        insertLayout.setVerticalGroup(
            insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(insertLayout.createSequentialGroup()
                        .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(enindex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(enfaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(encourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(insertLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(enchoice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ensemi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19)
                        .addComponent(enchoice2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(insertLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(enmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(insertLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, insertLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(encom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(enfee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(insertLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6)
                            .addComponent(encredits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(insertLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        update.setBackground(new java.awt.Color(51, 51, 51));

        jLabel9.setBackground(new java.awt.Color(51, 51, 51));
        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Index No  :");

        euindex.setBackground(new java.awt.Color(51, 51, 51));
        euindex.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        euindex.setForeground(new java.awt.Color(255, 255, 255));
        euindex.setBorder(null);
        euindex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                euindexActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(51, 51, 51));
        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Faculty  :");

        eufee.setBackground(new java.awt.Color(51, 51, 51));
        eufee.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        eufee.setForeground(new java.awt.Color(255, 255, 255));
        eufee.setBorder(null);

        jLabel11.setBackground(new java.awt.Color(51, 51, 51));
        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Credits  :");

        eufac.setBackground(new java.awt.Color(51, 51, 51));
        eufac.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        eufac.setForeground(new java.awt.Color(255, 255, 255));
        eufac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "School of Engineering", "School of Computing", "School of Business", " " }));
        eufac.setBorder(null);
        eufac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eufacActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(51, 51, 51));
        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Course  :");

        eucourse.setBackground(new java.awt.Color(51, 51, 51));
        eucourse.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        eucourse.setForeground(new java.awt.Color(255, 255, 255));
        eucourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Civil Engineering", "Electrical Engineering", "Electronic Engineering", "Computer Science", "Information Systems", "Business Management", "Marketing" }));
        eucourse.setBorder(null);
        eucourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eucourseActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(51, 51, 51));
        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Semister  :");

        eusemi.setBackground(new java.awt.Color(51, 51, 51));
        eusemi.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        eusemi.setForeground(new java.awt.Color(255, 255, 255));
        eusemi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semister 1", "Semister 2", "Semister 3", "Semister 4", "Semister 5", "Semister 6", "Semister 7", "Semister 8" }));
        eusemi.setBorder(null);
        eusemi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eusemiActionPerformed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(51, 51, 51));
        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Com sub code:");

        jLabel15.setBackground(new java.awt.Color(51, 51, 51));
        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Fee     :");

        eucredits.setBackground(new java.awt.Color(51, 51, 51));
        eucredits.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        eucredits.setForeground(new java.awt.Color(255, 255, 255));
        eucredits.setBorder(null);
        eucredits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eucreditsActionPerformed(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(51, 51, 51));
        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Choice subjects code1:");

        jButton7.setBackground(new java.awt.Color(51, 51, 51));
        jButton7.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("UPDATE");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel21.setBackground(new java.awt.Color(51, 51, 51));
        jLabel21.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Choice Sub Code2:");

        eucom.setBackground(new java.awt.Color(51, 51, 51));
        eucom.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        eucom.setForeground(new java.awt.Color(255, 255, 255));
        eucom.setBorder(null);

        eucho1.setBackground(new java.awt.Color(51, 51, 51));
        eucho1.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        eucho1.setForeground(new java.awt.Color(255, 255, 255));
        eucho1.setBorder(null);

        eucho2.setBackground(new java.awt.Color(51, 51, 51));
        eucho2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        eucho2.setForeground(new java.awt.Color(255, 255, 255));
        eucho2.setBorder(null);

        jLabel22.setBackground(new java.awt.Color(51, 51, 51));
        jLabel22.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("E-mail :");

        eumail.setBackground(new java.awt.Color(51, 51, 51));
        eumail.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        eumail.setForeground(new java.awt.Color(255, 255, 255));
        eumail.setBorder(null);

        jTable1.setBackground(new java.awt.Color(51, 51, 51));
        jTable1.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        eusearch.setBackground(new java.awt.Color(51, 51, 51));
        eusearch.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        eusearch.setForeground(new java.awt.Color(255, 255, 255));
        eusearch.setBorder(null);
        eusearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                eusearchKeyReleased(evt);
            }
        });

        jLabel23.setBackground(new java.awt.Color(51, 51, 51));
        jLabel23.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("SEARCH");

        javax.swing.GroupLayout updateLayout = new javax.swing.GroupLayout(update);
        update.setLayout(updateLayout);
        updateLayout.setHorizontalGroup(
            updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(updateLayout.createSequentialGroup()
                        .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(updateLayout.createSequentialGroup()
                                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel16))
                                .addGap(7, 7, 7)
                                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eucom, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(updateLayout.createSequentialGroup()
                                        .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(euindex, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(eumail, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jSeparator14, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(eucho2, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jSeparator13, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jSeparator11, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(eufac, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jSeparator12, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(eucho1, javax.swing.GroupLayout.Alignment.LEADING)))
                                        .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(updateLayout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(updateLayout.createSequentialGroup()
                                                        .addComponent(jLabel15)
                                                        .addGap(18, 18, 18)
                                                        .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(eufee, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addGroup(updateLayout.createSequentialGroup()
                                                        .addComponent(jLabel12)
                                                        .addGap(35, 35, 35)
                                                        .addComponent(eucourse, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(0, 0, Short.MAX_VALUE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(updateLayout.createSequentialGroup()
                                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(eucredits, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(updateLayout.createSequentialGroup()
                                                        .addComponent(jLabel13)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(eusemi, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(67, 67, 67))))))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addContainerGap(21, Short.MAX_VALUE))))
            .addGroup(updateLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addGap(186, 186, 186))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator15)
                    .addComponent(eusearch, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                .addGap(133, 133, 133))
        );
        updateLayout.setVerticalGroup(
            updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateLayout.createSequentialGroup()
                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(updateLayout.createSequentialGroup()
                        .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateLayout.createSequentialGroup()
                                        .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel15)
                                            .addGroup(updateLayout.createSequentialGroup()
                                                .addComponent(euindex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(30, 30, 30))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateLayout.createSequentialGroup()
                                        .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(eucredits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14))))
                            .addGroup(updateLayout.createSequentialGroup()
                                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(updateLayout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(jLabel9))
                                    .addGroup(updateLayout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(eufee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(22, 22, 22)))
                        .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(eufac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(eusemi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eucourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(updateLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(eucho1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)
                                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(updateLayout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(jLabel21))
                                    .addGroup(updateLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(eucho2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel22))
                            .addGroup(updateLayout.createSequentialGroup()
                                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(eucom, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(updateLayout.createSequentialGroup()
                                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE))
                                    .addGroup(updateLayout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                        .addComponent(eusearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(updateLayout.createSequentialGroup()
                        .addComponent(eumail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jLabel23))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        delete.setBackground(new java.awt.Color(51, 51, 51));

        jLabel24.setBackground(new java.awt.Color(51, 51, 51));
        jLabel24.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Index No :");

        edel.setBackground(new java.awt.Color(51, 51, 51));
        edel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        edel.setForeground(new java.awt.Color(255, 255, 255));
        edel.setBorder(null);

        jButton8.setBackground(new java.awt.Color(51, 51, 51));
        jButton8.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("DELETE");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deleteLayout = new javax.swing.GroupLayout(delete);
        delete.setLayout(deleteLayout);
        deleteLayout.setHorizontalGroup(
            deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteLayout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel24)
                .addGap(23, 23, 23)
                .addGroup(deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator16)
                    .addComponent(edel, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteLayout.createSequentialGroup()
                .addContainerGap(540, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(281, 281, 281))
        );
        deleteLayout.setVerticalGroup(
            deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(edel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(jButton8)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/en.PNG"))); // NOI18N

        javax.swing.GroupLayout dynamicpanel1Layout = new javax.swing.GroupLayout(dynamicpanel1);
        dynamicpanel1.setLayout(dynamicpanel1Layout);
        dynamicpanel1Layout.setHorizontalGroup(
            dynamicpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(insert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(dynamicpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(dynamicpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(dynamicpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(view, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(dynamicpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dynamicpanel1Layout.createSequentialGroup()
                    .addGap(86, 86, 86)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(42, Short.MAX_VALUE)))
        );
        dynamicpanel1Layout.setVerticalGroup(
            dynamicpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(insert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(dynamicpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(update, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(dynamicpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(delete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(dynamicpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(view, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(dynamicpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dynamicpanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        getContentPane().add(dynamicpanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 922, 450));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("INSERT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 110, -1));

        jButton4.setBackground(new java.awt.Color(51, 51, 51));
        jButton4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("VIEW");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 110, -1));

        jButton5.setBackground(new java.awt.Color(51, 51, 51));
        jButton5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("BACK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/copy111.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        insert.setVisible(true);
        update.setVisible(false);
        delete.setVisible(false);
        view.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        insert.setVisible(false);
        update.setVisible(true);
        delete.setVisible(false);
        view.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        insert.setVisible(false);
        update.setVisible(false);
        delete.setVisible(true);
        view.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        insert.setVisible(false);
        update.setVisible(false);
        delete.setVisible(false);
        view.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.hide();
        UndergraduateCourse uc=new UndergraduateCourse();
        uc.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void eusemiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eusemiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eusemiActionPerformed

    private void eufacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eufacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eufacActionPerformed

    private void eucourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eucourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eucourseActionPerformed

    private void encourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encourseActionPerformed
         //public void showenroll(){
        
            // TODO add your handling code here:
    }//GEN-LAST:event_encourseActionPerformed

    private void euindexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_euindexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_euindexActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connect=DriverManager.getConnection("jdbc:mysql://localhost:3306/login?zeroDateTimeBehavior=convertToNull","root","");
            String query="insert into enrollment(IndexNo,Faculty,Course,Semister,E_mail,Fee,Credits,ChoiceSubject1,ChoiceSubject2,CompulsarySubject)values(?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement st=connect.prepareStatement(query);
            st.setString(1,enindex.getText());
            String Faculty;
            Faculty=enfaculty.getSelectedItem().toString();
            st.setString(2,Faculty);
            String Course;
            Course=encourse.getSelectedItem().toString();
            st.setString(3,Course);
            String Semister;
            Semister=ensemi.getSelectedItem().toString();
            st.setString(4,Semister);
            st.setString(5,enmail.getText());
            st.setString(6,enfee.getText());
            st.setString(7,encredits.getText());
            st.setString(8,enchoice1.getText());
            st.setString(9,enchoice2.getText());
            st.setString(10,encom1.getText());
            
            st.executeUpdate();
            DefaultTableModel table=(DefaultTableModel)etable.getModel();
            table.setRowCount(0);
            showdetailsen();
            st.executeUpdate();
            JOptionPane.showMessageDialog(null,"inserted sucessfully");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }             // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void enmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enmailActionPerformed

    private void eusearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eusearchKeyReleased
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connect=DriverManager.getConnection("jdbc:mysql://localhost:3306/login?zeroDateTimeBehavior=convertToNull","root","");
            String query="select * from enrollment where IndexNo=?";
            PreparedStatement st=connect.prepareStatement(query);
            st.setString(1,eusearch.getText());
            ResultSet rst=st.executeQuery();
            if(rst.next()){
                euindex.setText(rst.getString("IndexNo"));
                String Faculty=rst.getString("Faculty");
                    switch(Faculty){
                        case"School of Engineering":
                            eufac.setSelectedIndex(0);
                            break;
                        case"School of Computing":
                            eufac.setSelectedIndex(1);
                            break;
                        case"School of Business":
                            eufac.setSelectedIndex(2);
                            break;
                    }
                String Course=rst.getString("Course");
                switch(Course){
                    case"Civil Engineering":
                        eucourse.setSelectedIndex(0);
                        break;
                    case"Electrical Engineering":
                        eucourse.setSelectedIndex(1);
                        break;
                    case"Computer Science":
                        eucourse.setSelectedIndex(2);
                        break;
                    case"Business Management":
                        eucourse.setSelectedIndex(3);
                        break;
                }
                String Semister=rst.getString("Semister");
                switch(Semister){
                    case"Semister1":
                        eusemi.setSelectedIndex(0);
                        break;
                    case"Semister2":
                        eusemi.setSelectedIndex(1);
                        break;
                    case"Semister3":
                        eusemi.setSelectedIndex(2);
                        break;
                    case"Semister4":
                        eusemi.setSelectedIndex(3);
                        break;
                    case"Semister5":
                        eusemi.setSelectedIndex(4);
                        break;
                    case"Semister6":
                        eusemi.setSelectedIndex(5);
                        break;
                    case"Semister7":
                        eusemi.setSelectedIndex(6);
                        break;
                    case"Semister8":
                        eusemi.setSelectedIndex(7);
                        break;
                }
                eumail.setText(rst.getString("E_mail"));
                eufee.setText(rst.getString("Fee"));
                eucredits.setText(rst.getString("Credits"));
                eucho1.setText(rst.getString("ChoiceSubject1"));
                eucho2.setText(rst.getString("ChoiceSubject2"));
                eucom.setText(rst.getString("CompulsarySubject"));
                
                
            }
            
               /* else{
                    JOptionPane.showMessageDialog(null,"Entered index number is incorrect");
                }*/
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_eusearchKeyReleased

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connect=DriverManager.getConnection("jdbc:mysql://localhost:3306/login?zeroDateTimeBehavior=convertToNull","root","");
            String query=("update enrollment set IndexNo=?,Faculty=?,Course=?,Semister=?,E_mail=?,Fee=?,Credits=?,ChoiceSubject1=?,ChoiceSubject2=?,CompulsarySubject=? where IndexNo='"+eusearch.getText())+"'";
            //int row=displaytable.getSelectedRow();
            //String value=(displaytable.getModel().getValueAt(row,0).toString());
            PreparedStatement st=connect.prepareStatement(query);
            st.setString(1,euindex.getText());
            String Faculty;
            Faculty=eufac.getSelectedItem().toString();
            st.setString(2,Faculty);
            String Course;
            Course=eucourse.getSelectedItem().toString();
            st.setString(3,Course);
            String Semister;
            Semister=eusemi.getSelectedItem().toString();
            st.setString(4,Semister);
         
            st.setString(5,eumail.getText());
            st.setString(6,eufee.getText());
            st.setString(7,eucredits.getText());
            st.setString(8,eucho1.getText());  
            st.setString(9,eucho2.getText());
            st.setString(10,eucom.getText());
            
            st.executeUpdate();
            DefaultTableModel table=(DefaultTableModel)etable.getModel();
            table.setRowCount(0);
            showdetailsen();
            JOptionPane.showMessageDialog(null,"updated sucessfully");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int delete=JOptionPane.showConfirmDialog(null,"Do you really want to delete?","Delete",JOptionPane.YES_NO_OPTION); 
        if(delete==0){
            String sql="delete from enrollment where IndexNo=?";
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection connect=DriverManager.getConnection("jdbc:mysql://localhost:3306/login?zeroDateTimeBehavior=convertToNull","root","");
                PreparedStatement st=connect.prepareStatement(sql);
                st.setString(1,edel.getText());
                st.executeUpdate();
                DefaultTableModel table=(DefaultTableModel)etable.getModel();
                table.setRowCount(0);
                showdetailsen();
                JOptionPane.showMessageDialog(null,"Deleted");
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void eucreditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eucreditsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eucreditsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(enrollment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(enrollment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(enrollment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(enrollment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new enrollment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel delete;
    private javax.swing.JPanel dynamicpanel1;
    private javax.swing.JTextField edel;
    private javax.swing.JTextField enchoice1;
    private javax.swing.JTextField enchoice2;
    private javax.swing.JTextField encom1;
    private javax.swing.JComboBox<String> encourse;
    private javax.swing.JTextField encredits;
    private javax.swing.JComboBox<String> enfaculty;
    private javax.swing.JTextField enfee;
    private javax.swing.JTextField enindex;
    private javax.swing.JTextField enmail;
    private javax.swing.JComboBox<String> ensemi;
    private javax.swing.JTable entable;
    private javax.swing.JTable etable;
    private javax.swing.JTextField eucho1;
    private javax.swing.JTextField eucho2;
    private javax.swing.JTextField eucom;
    private javax.swing.JComboBox<String> eucourse;
    private javax.swing.JTextField eucredits;
    private javax.swing.JComboBox<String> eufac;
    private javax.swing.JTextField eufee;
    private javax.swing.JTextField euindex;
    private javax.swing.JTextField eumail;
    private javax.swing.JTextField eusearch;
    private javax.swing.JComboBox<String> eusemi;
    private javax.swing.JPanel insert;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel update;
    private javax.swing.JPanel view;
    // End of variables declaration//GEN-END:variables
}
