
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hp
 */
public class PostgraduateRegistration extends javax.swing.JFrame {
    String PGender;
    
    /**
     * Creates new form PostgraduateRegistration
     */
    public PostgraduateRegistration() {
        initComponents();
        showpregdetails();
        dynamicpanel2.setVisible(true);
        insert.setVisible(false);
        update.setVisible(false);
        delete.setVisible(false);
        view.setVisible(false);
    }
    public ArrayList<pregdetails>pregList(){
        ArrayList<pregdetails>pregList=new ArrayList<>();
         try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connect=DriverManager.getConnection("jdbc:mysql://localhost:3306/login?zeroDateTimeBehavior=convertToNull","root","");
            String query="select * from postgraduateregistration";
            Statement st=connect.createStatement();
            ResultSet rst=st.executeQuery(query);
            pregdetails Pregdetails;
            while(rst.next()){
                Pregdetails=new pregdetails(rst.getString("IndexNo"), rst.getString("FullName"), rst.getString("DOB"), rst.getString("Gender"), rst.getString("Address"), rst.getString("NICNo"), rst.getInt("ContNo"), rst.getString("Qualification"), rst.getString("Institute"), rst.getString("YrCompletion"), rst.getString("Faculty"), rst.getString("Course"));
                pregList.add(Pregdetails);           
            }
         
         } 
         catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
         }
         return pregList;
    }
    public void showpregdetails(){
        ArrayList<pregdetails> list=pregList();
        DefaultTableModel table2=(DefaultTableModel)pview.getModel();
        Object[] row=new Object[12];
        for(int i=0;i<list.size();i++){
            row[0]=list.get(i).getIndexNo();
            row[1]=list.get(i).getFullName();
            row[2]=list.get(i).getDOB();
            row[3]=list.get(i).getGender();
            row[4]=list.get(i).getAddress();
            row[5]=list.get(i).getNICNo();
            row[6]=list.get(i).getContNo();
            row[7]=list.get(i).getQualification();
            row[8]=list.get(i).getInstitute();
            row[9]=list.get(i).getYrCompletion();
            row[10]=list.get(i).getFaculty();
            row[11]=list.get(i).getCourse();
            table2.addRow(row);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        dynamicpanel2 = new javax.swing.JPanel();
        insert = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pindexno = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        pname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        pdob = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pmale = new javax.swing.JRadioButton();
        pfemale = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        paddress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        pnicno = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        pcontno = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        pinsti = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        pcomple = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        pquali = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        pfaculty = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        pcourse = new javax.swing.JComboBox<>();
        update = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        pupindex = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        pupname = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        pupdob = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        pupaddress = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        pupmale = new javax.swing.JRadioButton();
        pupfemale = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        pupnic = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        pupcont = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        pupquali = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        pupinsti = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        pupcomple = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        pupfaculty = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        pupcourse = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        psearch = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        delete = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jSeparator20 = new javax.swing.JSeparator();
        eindex = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        view = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pview = new javax.swing.JTable();
        jLabel28 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dynamicpanel2.setBackground(new java.awt.Color(51, 51, 51));

        insert.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Index No  :");

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name :");

        pindexno.setBackground(new java.awt.Color(51, 51, 51));
        pindexno.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        pindexno.setForeground(new java.awt.Color(255, 255, 255));
        pindexno.setBorder(null);

        pname.setBackground(new java.awt.Color(51, 51, 51));
        pname.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        pname.setForeground(new java.awt.Color(255, 255, 255));
        pname.setBorder(null);

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DOB     :");

        pdob.setBackground(new java.awt.Color(51, 51, 51));
        pdob.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        pdob.setForeground(new java.awt.Color(255, 255, 255));
        pdob.setBorder(null);

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gender  :");

        pmale.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(pmale);
        pmale.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        pmale.setForeground(new java.awt.Color(255, 255, 255));
        pmale.setText("Male");

        pfemale.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(pfemale);
        pfemale.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        pfemale.setForeground(new java.awt.Color(255, 255, 255));
        pfemale.setText("Female");

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Address  :");

        paddress.setBackground(new java.awt.Color(51, 51, 51));
        paddress.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        paddress.setForeground(new java.awt.Color(255, 255, 255));
        paddress.setBorder(null);

        jLabel7.setBackground(new java.awt.Color(51, 51, 51));
        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NIC No  :");

        pnicno.setBackground(new java.awt.Color(51, 51, 51));
        pnicno.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        pnicno.setForeground(new java.awt.Color(255, 255, 255));
        pnicno.setBorder(null);

        jLabel8.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Contact No:");

        pcontno.setBackground(new java.awt.Color(51, 51, 51));
        pcontno.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        pcontno.setForeground(new java.awt.Color(255, 255, 255));
        pcontno.setBorder(null);

        jLabel9.setBackground(new java.awt.Color(51, 51, 51));
        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Qualfication:");

        jLabel10.setBackground(new java.awt.Color(51, 51, 51));
        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Institute    :");

        jLabel11.setBackground(new java.awt.Color(51, 51, 51));
        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Yr.Complete:");

        pinsti.setBackground(new java.awt.Color(51, 51, 51));
        pinsti.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        pinsti.setForeground(new java.awt.Color(255, 255, 255));
        pinsti.setBorder(null);

        pcomple.setBackground(new java.awt.Color(51, 51, 51));
        pcomple.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        pcomple.setForeground(new java.awt.Color(255, 255, 255));
        pcomple.setBorder(null);

        pquali.setBackground(new java.awt.Color(51, 51, 51));
        pquali.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        pquali.setForeground(new java.awt.Color(255, 255, 255));
        pquali.setBorder(null);

        jButton6.setBackground(new java.awt.Color(51, 51, 51));
        jButton6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("SAVE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(51, 51, 51));
        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Faculty :");

        pfaculty.setBackground(new java.awt.Color(51, 51, 51));
        pfaculty.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        pfaculty.setForeground(new java.awt.Color(255, 255, 255));
        pfaculty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "School of Engineering", "School of Computing", "School of Business", " " }));
        pfaculty.setBorder(null);

        jLabel13.setBackground(new java.awt.Color(51, 51, 51));
        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Course  :");

        pcourse.setBackground(new java.awt.Color(51, 51, 51));
        pcourse.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        pcourse.setForeground(new java.awt.Color(255, 255, 255));
        pcourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Civil Engineering", "Electrical Engineering", "Computer Science", "Business Management", " " }));
        pcourse.setBorder(null);

        javax.swing.GroupLayout insertLayout = new javax.swing.GroupLayout(insert);
        insert.setLayout(insertLayout);
        insertLayout.setHorizontalGroup(
            insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(insertLayout.createSequentialGroup()
                        .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(insertLayout.createSequentialGroup()
                                .addComponent(pmale)
                                .addGap(27, 27, 27)
                                .addComponent(pfemale)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, insertLayout.createSequentialGroup()
                                .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pnicno, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(paddress, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pdob, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, insertLayout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(pindexno, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pname, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(33, 33, 33)
                                .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(insertLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(pcomple))
                                    .addGroup(insertLayout.createSequentialGroup()
                                        .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13))
                                        .addGap(18, 18, 18)
                                        .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jSeparator7)
                                            .addComponent(pinsti)
                                            .addComponent(jSeparator8)
                                            .addComponent(pfaculty, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(pcourse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(241, 241, 241))))
                    .addGroup(insertLayout.createSequentialGroup()
                        .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(insertLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pquali, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, insertLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator9, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                    .addComponent(pcontno)
                                    .addComponent(jSeparator6))))
                        .addGap(198, 198, 198)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        insertLayout.setVerticalGroup(
            insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertLayout.createSequentialGroup()
                .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(insertLayout.createSequentialGroup()
                        .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(insertLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pindexno, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(insertLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(pinsti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(insertLayout.createSequentialGroup()
                                    .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(pname, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11)
                                        .addComponent(pcomple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(insertLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2)))
                .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(insertLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(pmale)
                            .addComponent(pfemale))
                        .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(insertLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))
                            .addGroup(insertLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(paddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(pcourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(insertLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel7))
                            .addGroup(insertLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(pnicno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(insertLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(pcontno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addComponent(jLabel9)
                                .addGap(0, 5, Short.MAX_VALUE))
                            .addGroup(insertLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pquali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(insertLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(pfaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        update.setBackground(new java.awt.Color(51, 51, 51));
        update.setPreferredSize(new java.awt.Dimension(830, 450));

        jLabel14.setBackground(new java.awt.Color(51, 51, 51));
        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Index No:");

        pupindex.setBackground(new java.awt.Color(51, 51, 51));
        pupindex.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        pupindex.setForeground(new java.awt.Color(255, 255, 255));
        pupindex.setBorder(null);

        jLabel15.setBackground(new java.awt.Color(51, 51, 51));
        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Full Name :");

        pupname.setBackground(new java.awt.Color(51, 51, 51));
        pupname.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        pupname.setForeground(new java.awt.Color(255, 255, 255));
        pupname.setBorder(null);

        jLabel16.setBackground(new java.awt.Color(51, 51, 51));
        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("DOB  :");

        pupdob.setBackground(new java.awt.Color(51, 51, 51));
        pupdob.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        pupdob.setForeground(new java.awt.Color(255, 255, 255));
        pupdob.setBorder(null);

        jLabel17.setBackground(new java.awt.Color(51, 51, 51));
        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Gender :");

        pupaddress.setBackground(new java.awt.Color(51, 51, 51));
        pupaddress.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        pupaddress.setForeground(new java.awt.Color(255, 255, 255));
        pupaddress.setBorder(null);

        jLabel18.setBackground(new java.awt.Color(51, 51, 51));
        jLabel18.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Address :");

        pupmale.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(pupmale);
        pupmale.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        pupmale.setForeground(new java.awt.Color(255, 255, 255));
        pupmale.setText("Male");

        pupfemale.setBackground(new java.awt.Color(51, 51, 51));
        pupfemale.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        pupfemale.setForeground(new java.awt.Color(255, 255, 255));
        pupfemale.setText("Female");

        jLabel19.setBackground(new java.awt.Color(51, 51, 51));
        jLabel19.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("NIC No :");

        pupnic.setBackground(new java.awt.Color(51, 51, 51));
        pupnic.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        pupnic.setForeground(new java.awt.Color(255, 255, 255));
        pupnic.setBorder(null);

        jLabel20.setBackground(new java.awt.Color(51, 51, 51));
        jLabel20.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Cont No :");

        pupcont.setBackground(new java.awt.Color(51, 51, 51));
        pupcont.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        pupcont.setForeground(new java.awt.Color(255, 255, 255));
        pupcont.setBorder(null);

        jLabel21.setBackground(new java.awt.Color(51, 51, 51));
        jLabel21.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Qualification :");

        pupquali.setBackground(new java.awt.Color(51, 51, 51));
        pupquali.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        pupquali.setForeground(new java.awt.Color(255, 255, 255));
        pupquali.setBorder(null);

        jLabel22.setBackground(new java.awt.Color(51, 51, 51));
        jLabel22.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Institute  :");

        pupinsti.setBackground(new java.awt.Color(51, 51, 51));
        pupinsti.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        pupinsti.setForeground(new java.awt.Color(255, 255, 255));
        pupinsti.setBorder(null);

        jLabel23.setBackground(new java.awt.Color(51, 51, 51));
        jLabel23.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Yr Compelte:");

        pupcomple.setBackground(new java.awt.Color(51, 51, 51));
        pupcomple.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        pupcomple.setForeground(new java.awt.Color(255, 255, 255));
        pupcomple.setBorder(null);

        jLabel24.setBackground(new java.awt.Color(51, 51, 51));
        jLabel24.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Faculty :");

        pupfaculty.setBackground(new java.awt.Color(51, 51, 51));
        pupfaculty.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        pupfaculty.setForeground(new java.awt.Color(255, 255, 255));
        pupfaculty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "School of Engineering ", "School of Computing ", "School of Business" }));
        pupfaculty.setBorder(null);

        jLabel25.setBackground(new java.awt.Color(51, 51, 51));
        jLabel25.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Course  :");

        pupcourse.setBackground(new java.awt.Color(51, 51, 51));
        pupcourse.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        pupcourse.setForeground(new java.awt.Color(255, 255, 255));
        pupcourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Civil Engineering", "Electrical Engineering", "Electronic Engineering", "Computer Science", "Infomation Systems", "Business Management", "Marketing", " " }));
        pupcourse.setBorder(null);

        jLabel26.setBackground(new java.awt.Color(51, 51, 51));
        jLabel26.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("SEARCH");

        psearch.setBackground(new java.awt.Color(51, 51, 51));
        psearch.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        psearch.setForeground(new java.awt.Color(255, 255, 255));
        psearch.setBorder(null);
        psearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                psearchKeyReleased(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(51, 51, 51));
        jButton7.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("UPDATE");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout updateLayout = new javax.swing.GroupLayout(update);
        update.setLayout(updateLayout);
        updateLayout.setHorizontalGroup(
            updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel14)
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addGap(24, 24, 24)
                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateLayout.createSequentialGroup()
                        .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(pupnic, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator13, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pupaddress, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator12, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pupdob, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator11, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pupname, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pupindex, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(76, 76, 76)
                        .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)))
                    .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pupcont, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                        .addComponent(jSeparator15, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(updateLayout.createSequentialGroup()
                        .addComponent(pupmale)
                        .addGap(38, 38, 38)
                        .addComponent(pupfemale)))
                .addGap(18, 18, 18)
                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pupinsti)
                    .addComponent(jSeparator17)
                    .addComponent(jSeparator18)
                    .addComponent(pupcomple)
                    .addComponent(pupfaculty, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pupcourse, 0, 206, Short.MAX_VALUE)
                    .addComponent(jSeparator19)
                    .addComponent(psearch))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(updateLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel21)
                .addGap(26, 26, 26)
                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator16, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(pupquali))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(74, 74, 74))
        );
        updateLayout.setVerticalGroup(
            updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateLayout.createSequentialGroup()
                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateLayout.createSequentialGroup()
                        .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(updateLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(pupindex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22))
                                .addGap(2, 2, 2)
                                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(updateLayout.createSequentialGroup()
                                        .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(updateLayout.createSequentialGroup()
                                                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(updateLayout.createSequentialGroup()
                                                        .addGap(19, 19, 19)
                                                        .addComponent(jLabel15))
                                                    .addGroup(updateLayout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(pupname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel23)
                                                            .addComponent(pupcomple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(jSeparator11, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                                                            .addComponent(jSeparator18))))
                                                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(updateLayout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(pupdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(updateLayout.createSequentialGroup()
                                                        .addGap(19, 19, 19)
                                                        .addComponent(jLabel16))))
                                            .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(pupfaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel24)))
                                        .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(updateLayout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel17)
                                                    .addComponent(pupmale)))
                                            .addGroup(updateLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(pupfemale)
                                                    .addComponent(jLabel25)
                                                    .addComponent(pupcourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(updateLayout.createSequentialGroup()
                                                .addComponent(pupaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateLayout.createSequentialGroup()
                                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(8, 8, 8)))
                                        .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(updateLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel19))
                                            .addGroup(updateLayout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(pupnic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel26)
                                                    .addComponent(psearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(4, 4, 4)
                                                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(3, 3, 3)
                                        .addComponent(pupcont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(7, 7, 7)
                                        .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pupinsti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(281, 281, 281)))
                        .addGap(20, 20, 20)
                        .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pupquali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateLayout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addGap(17, 17, 17)))
                .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        delete.setBackground(new java.awt.Color(51, 51, 51));

        jLabel27.setBackground(new java.awt.Color(51, 51, 51));
        jLabel27.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Index No  :");

        eindex.setBackground(new java.awt.Color(51, 51, 51));
        eindex.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        eindex.setForeground(new java.awt.Color(255, 255, 255));
        eindex.setBorder(null);

        jButton8.setBackground(new java.awt.Color(51, 51, 51));
        jButton8.setFont(new java.awt.Font("Comic Sans MS", 1, 19)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("DELETE");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deleteLayout = new javax.swing.GroupLayout(delete);
        delete.setLayout(deleteLayout);
        deleteLayout.setHorizontalGroup(
            deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteLayout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(jLabel27)
                .addGap(34, 34, 34)
                .addGroup(deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator20)
                    .addComponent(eindex, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                .addContainerGap(309, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(243, 243, 243))
        );
        deleteLayout.setVerticalGroup(
            deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(eindex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator20, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton8)
                .addContainerGap(268, Short.MAX_VALUE))
        );

        view.setBackground(new java.awt.Color(51, 51, 51));

        pview.setBackground(new java.awt.Color(51, 51, 51));
        pview.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        pview.setForeground(new java.awt.Color(255, 255, 255));
        pview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Index No", "Full Name", "DOB", "Gender", "Address", "NIC No", "Contact No", "Qualification", "Institute", "YrComplete", "Faculty", "Course"
            }
        ));
        jScrollPane1.setViewportView(pview);

        javax.swing.GroupLayout viewLayout = new javax.swing.GroupLayout(view);
        view.setLayout(viewLayout);
        viewLayout.setHorizontalGroup(
            viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );
        viewLayout.setVerticalGroup(
            viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
        );

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1490595614.jpg"))); // NOI18N

        javax.swing.GroupLayout dynamicpanel2Layout = new javax.swing.GroupLayout(dynamicpanel2);
        dynamicpanel2.setLayout(dynamicpanel2Layout);
        dynamicpanel2Layout.setHorizontalGroup(
            dynamicpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(insert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(dynamicpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(update, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE))
            .addGroup(dynamicpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(delete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(dynamicpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(view, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(dynamicpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dynamicpanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        dynamicpanel2Layout.setVerticalGroup(
            dynamicpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(insert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(dynamicpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(update, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE))
            .addGroup(dynamicpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(dynamicpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(view, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(dynamicpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dynamicpanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        getContentPane().add(dynamicpanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 830, 450));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("INSERT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 110, -1));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 110, -1));

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 110, -1));

        jButton4.setBackground(new java.awt.Color(51, 51, 51));
        jButton4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("VIEW");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 110, -1));

        jButton5.setBackground(new java.awt.Color(153, 153, 153));
        jButton5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton5.setText("BACK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/copyimagenew.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        insert.setVisible(true);
        update.setVisible(false);
        delete.setVisible(false);
        view.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        insert.setVisible(false);
        update.setVisible(true);
        delete.setVisible(false);
        view.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        insert.setVisible(false);
        update.setVisible(false);
        delete.setVisible(true);
        view.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        insert.setVisible(false);
        update.setVisible(false);
        delete.setVisible(false);
        view.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.hide();
        StudentDetail sd=new StudentDetail();
        sd.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connect=DriverManager.getConnection("jdbc:mysql://localhost:3306/login?zeroDateTimeBehavior=convertToNull","root","");
            String query="insert into postgraduateregistration(IndexNo,FullName,DOB,Gender,Address,NICNo,ContNo,Qualification,Institute,YrCompletion,Faculty,Course)values(?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement st=connect.prepareStatement(query);
            st.setString(1,pindexno.getText());
            st.setString(2,pname.getText());
            st.setString(3,pdob.getText());
            
            if(pmale.isSelected()){
                PGender = "Male";
            }
            if(pfemale.isSelected()){
                PGender = "Female";
            }
            st.setString(4,PGender);
            st.setString(5,paddress.getText());
            st.setString(6,pnicno.getText());
            st.setString(7,pcontno.getText());
            st.setString(8,pquali.getText());
            st.setString(9,pinsti.getText());
            st.setString(10,pcomple.getText());
            String Faculty;
            Faculty=pfaculty.getSelectedItem().toString();
            st.setString(11,Faculty);
            String Course;
            Course=pcourse.getSelectedItem().toString();
            st.setString(12,Course);
            st.executeUpdate();
            DefaultTableModel table=(DefaultTableModel)pview.getModel();
            table.setRowCount(0);
            showpregdetails();
            st.executeUpdate();
            
            //JOptionPane.showMessageDialog(null,"inserted sucessfully");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void psearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_psearchKeyReleased
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connect=DriverManager.getConnection("jdbc:mysql://localhost:3306/login?zeroDateTimeBehavior=convertToNull","root","");
            String query="select * from postgraduateregistration where IndexNo=?";
            PreparedStatement st=connect.prepareStatement(query);
            st.setString(1,psearch.getText());
            ResultSet rst=st.executeQuery();
            if(rst.next()){
                pupindex.setText(rst.getString("IndexNo"));
                pupname.setText(rst.getString("FullName"));
                pupdob.setText(rst.getString("DOB"));
                if(rst.getString("Gender").equals("Male")){
                    pupmale.setSelected(true);
                }
                else{
                    pupfemale.setSelected(true);
                }
                pupaddress.setText(rst.getString("Address"));
                pupnic.setText(rst.getString("NICNo"));
                pupcont.setText(rst.getString("ContNo"));
                pupquali.setText(rst.getString("Qualification"));
                pupinsti.setText(rst.getString("Institute"));
                pupcomple.setText(rst.getString("YrCompletion"));
                String Faculty=rst.getString("Faculty");
                    switch(Faculty){
                        case"School of Engineering":
                            pupfaculty.setSelectedIndex(0);
                            break;
                        case"School of Computing":
                            pupfaculty.setSelectedIndex(1);
                            break;
                        case"School of Business":
                            pupfaculty.setSelectedIndex(2);
                            break;
                    }
                String Course=rst.getString("Course");
                switch(Course){
                    case"Civil Engineering":
                        pupcourse.setSelectedIndex(0);
                        break;
                    case"Electrical Engineering":
                        pupcourse.setSelectedIndex(1);
                        break;
                    case"Computer Science":
                        pupcourse.setSelectedIndex(2);
                        break;
                    case"Business Management":
                        pupcourse.setSelectedIndex(3);
                        break;
                }
                
            }
            
               /* else{
                    JOptionPane.showMessageDialog(null,"Entered index number is incorrect");
                }*/
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }                   // TODO add your handling code here:
    }//GEN-LAST:event_psearchKeyReleased

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connect=DriverManager.getConnection("jdbc:mysql://localhost:3306/login?zeroDateTimeBehavior=convertToNull","root","");
            String query=("update postgraduateregistration set IndexNo=?,FullName=?,DOB=?,Gender=?,Address=?,NICNo=?,ContNo=?,Qualification=?,Institute=?,YrCompletion=?,Faculty=?,Course=? where IndexNo='"+psearch.getText())+"'";
            //int row=displaytable.getSelectedRow();
            //String value=(displaytable.getModel().getValueAt(row,0).toString());
            PreparedStatement st=connect.prepareStatement(query);
            st.setString(1,pupindex.getText());
            st.setString(2,pupname.getText());
            st.setString(3,pupdob.getText());
            String Gender=new String();
            if(pupmale.isSelected()){
                Gender = "Male";
            }
            if(pupfemale.isSelected()){
                Gender = "Female";
            }
            st.setString(4,Gender);
            st.setString(5,pupaddress.getText());
            st.setString(6,pupnic.getText());
            st.setString(7,pupcont.getText());
            st.setString(8,pupquali.getText());  
            st.setString(9,pupinsti.getText());
            st.setString(10,pupcomple.getText());
            String Faculty;
            Faculty=pupfaculty.getSelectedItem().toString();
            st.setString(11,Faculty);
            String Course;
            Course=pupcourse.getSelectedItem().toString();
            st.setString(12,Course);
            st.executeUpdate();
            DefaultTableModel table=(DefaultTableModel)pview.getModel();
            table.setRowCount(0);
            showpregdetails();
            JOptionPane.showMessageDialog(null,"updated sucessfully");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int delete=JOptionPane.showConfirmDialog(null,"Do you really want to delete?","Delete",JOptionPane.YES_NO_OPTION); 
        if(delete==0){
            String sql="delete from postgraduateregistration where IndexNo=?";
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection connect=DriverManager.getConnection("jdbc:mysql://localhost:3306/login?zeroDateTimeBehavior=convertToNull","root","");
                PreparedStatement st=connect.prepareStatement(sql);
                st.setString(1,eindex.getText());
                st.executeUpdate();
                DefaultTableModel table=(DefaultTableModel)pview.getModel();
                table.setRowCount(0);
                showpregdetails();
                JOptionPane.showMessageDialog(null,"Deleted");
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PostgraduateRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PostgraduateRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PostgraduateRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PostgraduateRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PostgraduateRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel delete;
    private javax.swing.JPanel dynamicpanel2;
    private javax.swing.JTextField eindex;
    private javax.swing.JPanel insert;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField paddress;
    private javax.swing.JTextField pcomple;
    private javax.swing.JTextField pcontno;
    private javax.swing.JComboBox<String> pcourse;
    private javax.swing.JTextField pdob;
    private javax.swing.JComboBox<String> pfaculty;
    private javax.swing.JRadioButton pfemale;
    private javax.swing.JTextField pindexno;
    private javax.swing.JTextField pinsti;
    private javax.swing.JRadioButton pmale;
    private javax.swing.JTextField pname;
    private javax.swing.JTextField pnicno;
    private javax.swing.JTextField pquali;
    private javax.swing.JTextField psearch;
    private javax.swing.JTextField pupaddress;
    private javax.swing.JTextField pupcomple;
    private javax.swing.JTextField pupcont;
    private javax.swing.JComboBox<String> pupcourse;
    private javax.swing.JTextField pupdob;
    private javax.swing.JComboBox<String> pupfaculty;
    private javax.swing.JRadioButton pupfemale;
    private javax.swing.JTextField pupindex;
    private javax.swing.JTextField pupinsti;
    private javax.swing.JRadioButton pupmale;
    private javax.swing.JTextField pupname;
    private javax.swing.JTextField pupnic;
    private javax.swing.JTextField pupquali;
    private javax.swing.JTable pview;
    private javax.swing.JPanel update;
    private javax.swing.JPanel view;
    // End of variables declaration//GEN-END:variables
}
