
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hp
 */
public class UndergraduateRegistration extends javax.swing.JFrame {
    String Gender;
    /**
     * Creates new form UndergraduateRegistration
     */
    public UndergraduateRegistration() {
        initComponents();
        showdetails();
        dynamicpanel.setVisible(true);
        insert.setVisible(false);
        delete.setVisible(false);
        view.setVisible(false);
        update.setVisible(false);
        
    }
    public ArrayList<details> userList(){
        ArrayList<details>userList=new ArrayList<>();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connect=DriverManager.getConnection("jdbc:mysql://localhost:3306/login?zeroDateTimeBehavior=convertToNull","root","");
            String query="select * from undergraduateregistration";
            Statement st=connect.createStatement();
            ResultSet rst=st.executeQuery(query);
            details Details;
            while(rst.next()){
                Details=new details(rst.getString("IndexNo"),rst.getString("FullName"),rst.getString("DOB"),rst.getString("Gender"),rst.getString("Address"),rst.getString("NICNo"),rst.getInt("ContNo"),rst.getString("ALresult"),rst.getInt("Rank"),rst.getString("Faculty"),rst.getString("Course"));
                userList.add(Details);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        return userList;
        
    }
    public void showdetails(){
        ArrayList<details>list=userList();
        DefaultTableModel table=(DefaultTableModel)displaytable.getModel();
        Object[] row=new Object[11];
        for(int k=0;k<list.size();k++){
            row[0]=list.get(k).getIndexNo();
            row[1]=list.get(k).getFullName();
            row[2]=list.get(k).getDOB();
            row[3]=list.get(k).getGender();
            row[4]=list.get(k).getAddress();
            row[5]=list.get(k).getNICNo();
            row[6]=list.get(k).getContNo();
            row[7]=list.get(k).getALresult();
            row[8]=list.get(k).getRank();
            row[9]=list.get(k).getFaculty();
            row[10]=list.get(k).getCourse();
            table.addRow(row);
            
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        dynamicpanel = new javax.swing.JPanel();
        insert = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        IndexNo = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        FullName = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        DOB = new javax.swing.JTextField();
        Male = new javax.swing.JRadioButton();
        Female = new javax.swing.JRadioButton();
        jSeparator4 = new javax.swing.JSeparator();
        Address = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        NICNo = new javax.swing.JTextField();
        ContNo = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        ALresult = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        Rank = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jButton6 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        faculty = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        course = new javax.swing.JComboBox<>();
        delete = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jSeparator17 = new javax.swing.JSeparator();
        uindex = new javax.swing.JTextField();
        view = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        displaytable = new javax.swing.JTable();
        update = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        upindex = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        upname = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        updob = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        upfemale = new javax.swing.JRadioButton();
        upmale = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        upaddress = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        upnic = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        upcont = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        upresult = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        uprank = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        index = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        upfaculty = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        upcourse = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dynamicpanel.setBackground(new java.awt.Color(51, 51, 51));
        dynamicpanel.setForeground(new java.awt.Color(255, 255, 255));
        dynamicpanel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        dynamicpanel.setName(""); // NOI18N

        insert.setBackground(new java.awt.Color(51, 51, 51));
        insert.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name        :");
        insert.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 77, -1, -1));

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Index No  :");
        insert.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 34, -1, -1));

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DOB          :");
        insert.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 116, -1, -1));

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Gender      :");
        insert.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 173, -1, -1));

        jLabel7.setBackground(new java.awt.Color(51, 51, 51));
        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Address    :");
        insert.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 216, -1, -1));

        jLabel8.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("NIC No     :");
        insert.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 260, -1, -1));

        jLabel9.setBackground(new java.awt.Color(51, 51, 51));
        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Contact No:");
        insert.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 306, -1, -1));

        jLabel10.setBackground(new java.awt.Color(51, 51, 51));
        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("A/L Result:");
        insert.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 355, -1, -1));

        jLabel12.setBackground(new java.awt.Color(51, 51, 51));
        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Rank         :");
        insert.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 410, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        insert.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 56, 241, 10));

        IndexNo.setBackground(new java.awt.Color(51, 51, 51));
        IndexNo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        IndexNo.setForeground(new java.awt.Color(255, 255, 255));
        IndexNo.setBorder(null);
        insert.add(IndexNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 34, 241, -1));

        jSeparator2.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        insert.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 101, 241, 9));

        FullName.setBackground(new java.awt.Color(51, 51, 51));
        FullName.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        FullName.setForeground(new java.awt.Color(255, 255, 255));
        FullName.setBorder(null);
        FullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FullNameActionPerformed(evt);
            }
        });
        insert.add(FullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 77, 240, -1));
        insert.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 149, 241, 10));

        DOB.setBackground(new java.awt.Color(51, 51, 51));
        DOB.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        DOB.setForeground(new java.awt.Color(255, 255, 255));
        DOB.setBorder(null);
        insert.add(DOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 116, 241, -1));

        Male.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(Male);
        Male.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Male.setForeground(new java.awt.Color(255, 255, 255));
        Male.setText("Male");
        Male.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        insert.add(Male, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 169, -1, -1));

        Female.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(Female);
        Female.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Female.setForeground(new java.awt.Color(255, 255, 255));
        Female.setText("Female");
        insert.add(Female, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 169, -1, -1));
        insert.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 238, 241, 11));

        Address.setBackground(new java.awt.Color(51, 51, 51));
        Address.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Address.setForeground(new java.awt.Color(255, 255, 255));
        Address.setBorder(null);
        insert.add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 216, 241, -1));
        insert.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 282, 241, 11));

        NICNo.setBackground(new java.awt.Color(51, 51, 51));
        NICNo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        NICNo.setForeground(new java.awt.Color(255, 255, 255));
        NICNo.setBorder(null);
        insert.add(NICNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 260, 241, -1));

        ContNo.setBackground(new java.awt.Color(51, 51, 51));
        ContNo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        ContNo.setForeground(new java.awt.Color(255, 255, 255));
        ContNo.setBorder(null);
        ContNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContNoActionPerformed(evt);
            }
        });
        insert.add(ContNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 299, 241, -1));

        jSeparator6.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        insert.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 326, 241, 10));

        ALresult.setBackground(new java.awt.Color(51, 51, 51));
        ALresult.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        ALresult.setForeground(new java.awt.Color(255, 255, 255));
        ALresult.setBorder(null);
        insert.add(ALresult, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 347, 241, -1));

        jSeparator7.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        insert.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 374, 241, 10));

        Rank.setBackground(new java.awt.Color(51, 51, 51));
        Rank.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Rank.setForeground(new java.awt.Color(255, 255, 255));
        Rank.setBorder(null);
        insert.add(Rank, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 402, 241, -1));

        jSeparator8.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        insert.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 429, 241, 12));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(51, 51, 51));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/image002.png"))); // NOI18N
        jButton6.setText("SAVE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        insert.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, 110, 30));

        jLabel21.setBackground(new java.awt.Color(51, 51, 51));
        jLabel21.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Faculty :");
        insert.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, -1, 20));

        faculty.setBackground(new java.awt.Color(102, 102, 102));
        faculty.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        faculty.setForeground(new java.awt.Color(255, 255, 255));
        faculty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "School of Engineering", "School of Computing", "School of Business", " " }));
        faculty.setBorder(null);
        insert.add(faculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 160, -1));

        jLabel23.setBackground(new java.awt.Color(51, 51, 51));
        jLabel23.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Course  :");
        insert.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, -1, -1));

        course.setBackground(new java.awt.Color(51, 51, 51));
        course.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        course.setForeground(new java.awt.Color(255, 255, 255));
        course.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Civil Engineering", "Electrical Engineering", "Computer Science", "Business Management" }));
        insert.add(course, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 160, -1));

        delete.setBackground(new java.awt.Color(51, 51, 51));

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Enter the Name:");

        jButton7.setBackground(new java.awt.Color(51, 51, 51));
        jButton7.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Delete");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        uindex.setBackground(new java.awt.Color(51, 51, 51));
        uindex.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        uindex.setForeground(new java.awt.Color(255, 255, 255));
        uindex.setBorder(null);

        javax.swing.GroupLayout deleteLayout = new javax.swing.GroupLayout(delete);
        delete.setLayout(deleteLayout);
        deleteLayout.setHorizontalGroup(
            deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteLayout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jLabel4)
                .addGap(40, 40, 40)
                .addGroup(deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator17)
                    .addComponent(uindex, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                .addContainerGap(251, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(103, 103, 103))
        );
        deleteLayout.setVerticalGroup(
            deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(uindex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jButton7)
                .addContainerGap(210, Short.MAX_VALUE))
        );

        view.setBackground(new java.awt.Color(51, 51, 51));

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        displaytable.setBackground(new java.awt.Color(51, 51, 51));
        displaytable.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        displaytable.setForeground(new java.awt.Color(255, 255, 255));
        displaytable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Index No", "Full Name", "DOB", "Gender", "Address", "NIC No", "Contact No", "A/L Result", "Z-Score", "Faculty", "Course"
            }
        ));
        jScrollPane1.setViewportView(displaytable);

        javax.swing.GroupLayout viewLayout = new javax.swing.GroupLayout(view);
        view.setLayout(viewLayout);
        viewLayout.setHorizontalGroup(
            viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
        );
        viewLayout.setVerticalGroup(
            viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
        );

        update.setBackground(new java.awt.Color(51, 51, 51));

        jLabel11.setBackground(new java.awt.Color(51, 51, 51));
        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Index No  :");

        jSeparator9.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator9.setForeground(new java.awt.Color(255, 255, 255));

        upindex.setBackground(new java.awt.Color(51, 51, 51));
        upindex.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        upindex.setForeground(new java.awt.Color(255, 255, 255));
        upindex.setBorder(null);
        upindex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upindexActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(51, 51, 51));
        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Name        :");

        jSeparator10.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator10.setForeground(new java.awt.Color(255, 255, 255));

        upname.setBackground(new java.awt.Color(51, 51, 51));
        upname.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        upname.setForeground(new java.awt.Color(255, 255, 255));
        upname.setBorder(null);
        upname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upnameActionPerformed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(51, 51, 51));
        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("DOB           :");

        jSeparator11.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator11.setForeground(new java.awt.Color(255, 255, 255));

        updob.setBackground(new java.awt.Color(51, 51, 51));
        updob.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        updob.setForeground(new java.awt.Color(255, 255, 255));
        updob.setBorder(null);
        updob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updobActionPerformed(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(51, 51, 51));
        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Gender     :");

        upfemale.setBackground(new java.awt.Color(51, 51, 51));
        upfemale.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        upfemale.setForeground(new java.awt.Color(255, 255, 255));
        upfemale.setText("Female");
        upfemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upfemaleActionPerformed(evt);
            }
        });

        upmale.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(upmale);
        upmale.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        upmale.setForeground(new java.awt.Color(255, 255, 255));
        upmale.setText("Male");
        upmale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upmaleActionPerformed(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(51, 51, 51));
        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Address      :");

        jSeparator12.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator12.setForeground(new java.awt.Color(255, 255, 255));

        upaddress.setBackground(new java.awt.Color(51, 51, 51));
        upaddress.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        upaddress.setForeground(new java.awt.Color(255, 255, 255));
        upaddress.setBorder(null);
        upaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upaddressActionPerformed(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(51, 51, 51));
        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("NIC No       :");

        jSeparator13.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator13.setForeground(new java.awt.Color(255, 255, 255));

        upnic.setBackground(new java.awt.Color(51, 51, 51));
        upnic.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        upnic.setForeground(new java.awt.Color(255, 255, 255));
        upnic.setBorder(null);
        upnic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upnicActionPerformed(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(51, 51, 51));
        jLabel18.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Contact No :");

        jSeparator14.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator14.setForeground(new java.awt.Color(255, 255, 255));

        upcont.setBackground(new java.awt.Color(51, 51, 51));
        upcont.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        upcont.setForeground(new java.awt.Color(255, 255, 255));
        upcont.setBorder(null);

        jLabel19.setBackground(new java.awt.Color(51, 51, 51));
        jLabel19.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("A/L Result :");

        jSeparator15.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator15.setForeground(new java.awt.Color(255, 255, 255));

        upresult.setBackground(new java.awt.Color(51, 51, 51));
        upresult.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        upresult.setForeground(new java.awt.Color(255, 255, 255));
        upresult.setBorder(null);
        upresult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upresultActionPerformed(evt);
            }
        });

        jLabel20.setBackground(new java.awt.Color(51, 51, 51));
        jLabel20.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Rank     :");

        uprank.setBackground(new java.awt.Color(51, 51, 51));
        uprank.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        uprank.setForeground(new java.awt.Color(255, 255, 255));
        uprank.setBorder(null);
        uprank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uprankActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(102, 102, 102));
        jButton8.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(51, 51, 51));
        jButton8.setText("UPDATE");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel22.setBackground(new java.awt.Color(51, 51, 51));
        jLabel22.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("SEARCH");

        jSeparator18.setForeground(new java.awt.Color(255, 255, 255));

        index.setBackground(new java.awt.Color(51, 51, 51));
        index.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        index.setForeground(new java.awt.Color(255, 255, 255));
        index.setBorder(null);
        index.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                indexMouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                indexMouseReleased(evt);
            }
        });
        index.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                indexKeyReleased(evt);
            }
        });

        jLabel24.setBackground(new java.awt.Color(51, 51, 51));
        jLabel24.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Faculty :");

        upfaculty.setBackground(new java.awt.Color(51, 51, 51));
        upfaculty.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        upfaculty.setForeground(new java.awt.Color(255, 255, 255));
        upfaculty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "School of Engineering", "School of Computing", "School of Business" }));

        jLabel25.setBackground(new java.awt.Color(51, 51, 51));
        jLabel25.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Course :");

        upcourse.setBackground(new java.awt.Color(51, 51, 51));
        upcourse.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        upcourse.setForeground(new java.awt.Color(255, 255, 255));
        upcourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Civil Engineering", "Electrical Engineering", "Electronic Engineering", "Computer Science", "Information Systems", "Business Management", "Marketing" }));

        javax.swing.GroupLayout updateLayout = new javax.swing.GroupLayout(update);
        update.setLayout(updateLayout);
        updateLayout.setHorizontalGroup(
            updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateLayout.createSequentialGroup()
                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(updateLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))))
                .addGap(32, 32, 32)
                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateLayout.createSequentialGroup()
                        .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator13)
                            .addComponent(upnic)
                            .addComponent(jSeparator12)
                            .addComponent(upaddress, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator14)
                            .addComponent(jSeparator15)
                            .addComponent(upresult, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(upcont, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(updateLayout.createSequentialGroup()
                                .addGap(210, 210, 210)
                                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jSeparator16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                    .addComponent(uprank, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(updateLayout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(updateLayout.createSequentialGroup()
                                        .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel22))
                                        .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(updateLayout.createSequentialGroup()
                                                .addGap(52, 52, 52)
                                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(index, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                    .addGroup(updateLayout.createSequentialGroup()
                        .addComponent(upfemale)
                        .addGap(77, 77, 77)
                        .addComponent(upmale))
                    .addGroup(updateLayout.createSequentialGroup()
                        .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(updob, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(jSeparator10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(upname, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator11, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(upindex, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator9, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(117, 117, 117)
                        .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(updateLayout.createSequentialGroup()
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(upcourse, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(updateLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(18, 18, 18)
                                .addComponent(upfaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        updateLayout.setVerticalGroup(
            updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateLayout.createSequentialGroup()
                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(updateLayout.createSequentialGroup()
                        .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(updateLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(upindex, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(updateLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel24)
                                        .addComponent(upfaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel11))))
                        .addGap(2, 2, 2)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(updateLayout.createSequentialGroup()
                                .addComponent(upname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel25)
                        .addComponent(upcourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(updateLayout.createSequentialGroup()
                        .addComponent(updob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(upfemale)
                    .addComponent(upmale)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uprank, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(upaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(index, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(updateLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateLayout.createSequentialGroup()
                        .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jButton8))
                    .addGroup(updateLayout.createSequentialGroup()
                        .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(upnic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(upcont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(upresult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1490595614.jpg"))); // NOI18N

        javax.swing.GroupLayout dynamicpanelLayout = new javax.swing.GroupLayout(dynamicpanel);
        dynamicpanel.setLayout(dynamicpanelLayout);
        dynamicpanelLayout.setHorizontalGroup(
            dynamicpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(insert, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        dynamicpanelLayout.setVerticalGroup(
            dynamicpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(insert, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(dynamicpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 0, 830, 450));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("INSERT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 120, 40));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 120, -1));

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("VIEW");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 120, -1));

        jButton5.setBackground(new java.awt.Color(153, 153, 153));
        jButton5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton5.setText("BACK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        jButton4.setBackground(new java.awt.Color(51, 51, 51));
        jButton4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("UPDATE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 120, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/copyimagenew.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        insert.setVisible(true);
        delete.setVisible(false);
        view.setVisible(false);
        update.setVisible(false);
       // dynamicpanel.setVisible(false);
        //add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //dynamicpanel.setVisible(false);
        insert.setVisible(false);
        delete.setVisible(true);
        view.setVisible(false);
        update.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ContNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContNoActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connect=DriverManager.getConnection("jdbc:mysql://localhost:3306/login?zeroDateTimeBehavior=convertToNull","root","");
            String query="insert into undergraduateregistration(IndexNo,FullName,DOB,Gender,Address,NICNo,ContNo,ALresult,Rank,Faculty,Course)values(?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement st=connect.prepareStatement(query);
            st.setString(1,IndexNo.getText());
            st.setString(2,FullName.getText());
            st.setString(3,DOB.getText());
            if(Male.isSelected()){
                Gender = "Male";
            }
            if(Female.isSelected()){
                Gender = "Female";
            }
            st.setString(4,Gender);
            st.setString(5,Address.getText());
            st.setString(6,NICNo.getText());
            st.setString(7,ContNo.getText());
            st.setString(8,ALresult.getText());
            st.setString(9,Rank.getText());
            String Faculty;
            Faculty=faculty.getSelectedItem().toString();
            st.setString(10,Faculty);
            String Course;
            Course=course.getSelectedItem().toString();
            st.setString(11,Course);
            st.executeUpdate();
            DefaultTableModel table=(DefaultTableModel)displaytable.getModel();
            table.setRowCount(0);
            showdetails();
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }// TODO         // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.hide();
        StudentDetail sd=new StudentDetail();
        sd.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int delete=JOptionPane.showConfirmDialog(null,"Do you really want to delete?","Delete",JOptionPane.YES_NO_OPTION); 
        if(delete==0){
            String sql="delete from undergraduateregistration where IndexNo=?";
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection connect=DriverManager.getConnection("jdbc:mysql://localhost:3306/login?zeroDateTimeBehavior=convertToNull","root","");
                PreparedStatement st=connect.prepareStatement(sql);
                st.setString(1,uindex.getText());
                st.executeUpdate();
                DefaultTableModel table=(DefaultTableModel)displaytable.getModel();
                table.setRowCount(0);
                showdetails();
                JOptionPane.showMessageDialog(null,"Deleted");
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }   
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      //  dynamicpanel.setVisible(false);
        insert.setVisible(false);
        delete.setVisible(false);
        view.setVisible(true);
        update.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //dynamicpanel.setVisible(false);
        insert.setVisible(false);
        delete.setVisible(false);
        view.setVisible(false);
        update.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void updobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updobActionPerformed

    private void upresultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upresultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upresultActionPerformed

    private void uprankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uprankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uprankActionPerformed

    private void upmaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upmaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upmaleActionPerformed

    private void upfemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upfemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upfemaleActionPerformed

    private void upaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upaddressActionPerformed

    private void upnicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upnicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upnicActionPerformed

    private void upindexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upindexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upindexActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connect=DriverManager.getConnection("jdbc:mysql://localhost:3306/login?zeroDateTimeBehavior=convertToNull","root","");
            String query="update undergraduateregistration set IndexNo=?,FullName=?,DOB=?,Gender=?,Address=?,NICNo=?,ContNo=?,ALresult=?,Rank=?,Faculty=?,Course=? where IndexNo='"+index.getText()+"'";
            //int row=displaytable.getSelectedRow();
            //String value=(displaytable.getModel().getValueAt(row,0).toString());
            PreparedStatement st=connect.prepareStatement(query);
            st.setString(1,upindex.getText());
            st.setString(2,upname.getText());
            st.setString(3,updob.getText());
            String Gender=new String();
            if(upmale.isSelected()){
                Gender = "Male";
            }
            if(upfemale.isSelected()){
                Gender = "Female";
            }
            st.setString(4,Gender);
            st.setString(5,upaddress.getText());
            st.setString(6,upnic.getText());
            st.setString(7,upcont.getText());
            st.setString(8,upresult.getText());  
            st.setString(9,uprank.getText());
            String Faculty;
            Faculty=upfaculty.getSelectedItem().toString();
            st.setString(10,Faculty);
            String Course;
            Course=upcourse.getSelectedItem().toString();
            st.setString(11,Course);
            st.executeUpdate();
            DefaultTableModel table=(DefaultTableModel)displaytable.getModel();
            table.setRowCount(0);
            showdetails();
            JOptionPane.showMessageDialog(null,"updated sucessfully");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }    

    }//GEN-LAST:event_jButton8ActionPerformed

    private void indexMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_indexMouseReleased
   
           // else{
           //     JOptionPane.showMessageDialog(null,"Your entered Index number is incorrect");
             // TODO add your handling code here:
    }//GEN-LAST:event_indexMouseReleased

    private void upnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upnameActionPerformed

    private void indexMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_indexMouseEntered
                     // TODO add your handling code here:
    }//GEN-LAST:event_indexMouseEntered

    private void indexKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_indexKeyReleased
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connect=DriverManager.getConnection("jdbc:mysql://localhost:3306/login?zeroDateTimeBehavior=convertToNull","root","");
            String query="select * from undergraduateregistration where IndexNo=?";
            PreparedStatement st=connect.prepareStatement(query);
            st.setString(1,index.getText());
            ResultSet rst=st.executeQuery();
            if(rst.next()){
                upindex.setText(rst.getString("IndexNo"));
                upname.setText(rst.getString("FullName"));
                updob.setText(rst.getString("DOB"));
                if(rst.getString("Gender").equals("Male")){
                    upmale.setSelected(true);
                }
                else{
                    upfemale.setSelected(true);
                }
                upaddress.setText(rst.getString("Address"));
                upnic.setText(rst.getString("NICNo"));
                upcont.setText(rst.getString("ContNo"));
                upresult.setText(rst.getString("ALresult"));
                uprank.setText(rst.getString("Rank"));
                String Faculty=rst.getString("Faculty");
                    switch(Faculty){
                        case"School of Engineering":
                            upfaculty.setSelectedIndex(0);
                            break;
                        case"School of Computing":
                            upfaculty.setSelectedIndex(1);
                            break;
                        case"School of Business":
                            upfaculty.setSelectedIndex(2);
                            break;
                    }
                String Course=rst.getString("Course");
                switch(Course){
                    case"Civil Engineering":
                        upcourse.setSelectedIndex(0);
                        break;
                    case"Electrical Engineering":
                        upcourse.setSelectedIndex(1);
                        break;
                    case"Computer Science":
                        upcourse.setSelectedIndex(2);
                        break;
                    case"Business Management":
                        upcourse.setSelectedIndex(3);
                        break;
                }
                
            }
            
               /* else{
                    JOptionPane.showMessageDialog(null,"Entered index number is incorrect");
                }*/
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }           // TODO add your handling code here:
    }//GEN-LAST:event_indexKeyReleased

    private void FullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FullNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UndergraduateRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UndergraduateRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UndergraduateRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UndergraduateRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UndergraduateRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ALresult;
    private javax.swing.JTextField Address;
    private javax.swing.JTextField ContNo;
    private javax.swing.JTextField DOB;
    private javax.swing.JRadioButton Female;
    private javax.swing.JTextField FullName;
    private javax.swing.JTextField IndexNo;
    private javax.swing.JRadioButton Male;
    private javax.swing.JTextField NICNo;
    private javax.swing.JTextField Rank;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> course;
    private javax.swing.JPanel delete;
    private javax.swing.JTable displaytable;
    private javax.swing.JPanel dynamicpanel;
    private javax.swing.JComboBox<String> faculty;
    private javax.swing.JTextField index;
    private javax.swing.JPanel insert;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField uindex;
    private javax.swing.JTextField upaddress;
    private javax.swing.JTextField upcont;
    private javax.swing.JComboBox<String> upcourse;
    private javax.swing.JPanel update;
    private javax.swing.JTextField updob;
    private javax.swing.JComboBox<String> upfaculty;
    private javax.swing.JRadioButton upfemale;
    private javax.swing.JTextField upindex;
    private javax.swing.JRadioButton upmale;
    private javax.swing.JTextField upname;
    private javax.swing.JTextField upnic;
    private javax.swing.JTextField uprank;
    private javax.swing.JTextField upresult;
    private javax.swing.JPanel view;
    // End of variables declaration//GEN-END:variables
}
